# Generated by Django 4.2.10 on 2026-09-23 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, default='', help_text='Mobile number for Farmer / Admin login and WhatsApp alerts.', max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits, optional leading +).', regex='^\\+?[0-9]{10,15}$')], verbose_name='Admin Mobile Number'),
        ),
    ]
