services:
  - type: web
    name: farmstore
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate && python manage.py auto_init && gunicorn config.wsgi:application --workers 3 --threads 2"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: WHATSAPP_PROVIDER
        value: "console"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.10.14"

