# Generated by Django 6.1.1 on 2026-09-08 03:03

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, help_text='e.g. farmer@upi', max_length=100)),
                ('upi_display_name', models.CharField(blank=True, max_length=100)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to=apps.payments.models.qr_code_upload_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payment settings',
            },
        ),
    ]
