# Generated by Django 6.1.1 on 2026-09-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='farmer_whatsapp_number',
            field=models.CharField(blank=True, help_text='Where new-order WhatsApp alerts are sent (Phase 8).', max_length=16),
        ),
    ]
