# Generated by Django 6.1.1 on 2026-09-07 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('stock_added', 'Stock Added'), ('stock_adjustment', 'Stock Adjustment'), ('order_reserved', 'Order Reserved'), ('order_cancelled', 'Order Cancelled'), ('order_completed', 'Order Completed')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Signed amount. Positive increases available stock, negative decreases it.', max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Optional external reference, e.g. an order number (orders app added in Phase 5).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='inventory_i_product_c769c0_idx')],
            },
        ),
    ]
