# Generated by Django 6.1.1 on 2026-09-11 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('notification_type', models.CharField(choices=[('new_product_available', 'New Product Available'), ('new_stock_available', 'New Stock Available'), ('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_rejected', 'Order Rejected'), ('delivery_date_assigned', 'Delivery Date Assigned'), ('order_out_for_delivery', 'Order Out for Delivery'), ('order_delivered', 'Order Delivered'), ('farmer_new_order_alert', 'Farmer: New Order Alert')], max_length=30)),
                ('message_template_id', models.CharField(blank=True, max_length=100)),
                ('message_preview', models.CharField(blank=True, max_length=255)),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='orders.order')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='catalog.product')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['notification_type', '-sent_at'], name='notificatio_notific_bbc4b0_idx')],
            },
        ),
    ]
