# Generated by Django 4.2.10 on 2026-09-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrecord',
            name='delivery_status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('simulated', 'Simulated')], max_length=15),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='message_preview',
            field=models.TextField(blank=True),
        ),
    ]
